defaults:
  - local_system: ${oc.env:CMB_SIMS_LOCAL_SYSTEM}
  - file_system : common_fs
  - simulation  : base_sim
  - splits      : three_three
  - override hydra/job_logging: custom_log_with_extra_seed
  - _self_

create_dirs: false
force_new_noise_cache: true
dataset_name: TQU_32_3_3
seed_base_string: 'TQU-32-3-3'
hydra:
  run:
    dir: creation_logs/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir: creation_logs_multirun/${now:%Y-%m-%d-%H-%M-%S}
  verbose: true